services:
  - type: web
    name: eshady-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server_api_fastapi:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ESHADY_SECRET_KEY
        value: change-me
